print("由于表格的种类繁多, 我对表格进行了格式的统一,")
print("具体分为两类:横类, 和竖类,")
print("两类模板见: 横类模板.xlsx, 竖类模板.xlsx")
print("json文件格式模板见: json格式模板.json\n")
print("特别注意!!")
print("以我做的所有农产品表格为例,只有番茄是横类")
print("运行代码时请注意区分类别,运行相应的代码,注意输入文件后缀名\n")
print("对运行结果的说明:")
print("1.json数据存放在xxx_json.txt文件中, xxx为excel文件名")
print("2.一个excel文件生成一个txt文件,一个sheet生成一个json,所有的json存放在一个txt中")
